### ISSUE TITLE
Icons do not display correctly with this plugin enabled

### ISSUE THREAD

**Issue by thisdotrob** [hax/js-refactor#16]
For some reason when I enable this plugin all the icons in atom do not display (instead they are rendered as empty boxes). For example the icons in the tree view, the icons for collapsing code blocks and the category icons in the preferences panel.

**Comment by PurpleMagick** [comment]
I've got the same issue. It took me ages to find out, since I started disabling plugins in order of likelyhood and js-refactor was pretty far down the list.

~~Worth noting that there is a work around - disable the plugin before shutting down Atom -> start the editor again -> enable the plugin.~~

Actually - scratch that - if you activate the plugin while Atom is running, it doesn't take effect.

**Comment by ffxsam** [comment]
I also noticed this. Very strange. Removing this package for now.

**Comment by PurpleMagick** [comment]
It's a really bizarre issue. I keep getting it off and on - sometimes it would happen all the time, sometimes Atom just works. It might be something to do with timings. However, I _think_ I do have a workaround now.
1. Disable the **refactor** package NOT **js-refactor** - leave that enabled.
2. Reload the editor.
3. Re-enable **refactor**.

This seems to work on a relatively consistent basis. Then again, sometimes the icons and the packages work together without me doing anything, so I don't have total confidence this is a reliable workaround.

**Comment by lorensr** [comment]
This is still an issue for me on latest:

![image](https://cloud.githubusercontent.com/assets/251288/20159754/bf4d0fe0-a6b0-11e6-9604-36a7cf1a6d78.png)

**Comment by zaaack** [comment]
still here in linux

**Comment by hajoeun** [comment]
still here in macOS too.
