### ISSUE TITLE
Resource requests are cancelled if package is enabled

### ISSUE THREAD

**Issue by nerdgore** [hax/js-refactor#18]
If I have the js-refactor package enabled a lot of requests are cancelled. I can predictably reproduce the issue by enabling/disabling the package and reloading the window.

I noticed this originally due to missing file icons as described in #16, digging deeper I found the relation to this package.

See DanBrooker/file-icons#416

![screen shot 2016-08-10 at 17 11 29](https://cloud.githubusercontent.com/assets/1582533/17560853/e57f58f0-5f23-11e6-9726-ec2530581e72.png)

**Comment by qqilihq** [comment]
Can confirm this very nasty issue. I had troubles with missing icons on the Mac since a while, and disabling the js-refactor plugin finally solved this problem.

**Comment by Alhadis** [comment]
[Another confirmation](https://github.com/DanBrooker/file-icons/issues/423#issuecomment-250707633).

@hax This needs to be looked at. It's quite a serious issue, and has the potential to confuse the maintainers of a lot of packages whose fonts are being affected by this.

**Comment by codyzu** [comment]
I just uninstalled and re-installed this package and my font/icon issues are resolved for the moment. If you haven't already tried, it might be worth it... I'll write more if the issue comes back related to this package.

EDIT: No, the issue came back and this time uninstall/install does not fix it... disabling until there is a real fix.
